# 单节点Eureka
server:
  port: 7900

eureka:
  instance:
    hostname: registrar
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://registrar:7900/eureka/

spring:
  application:
    name: Eureka